package br.com.ufla.sgsr.view;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import br.com.ufla.sgsr.model.Aluno;
import br.com.ufla.sgsr.model.Professor;
import br.com.ufla.sgsr.model.Reserva;
import br.com.ufla.sgsr.model.Sala;
import br.com.ufla.sgsr.model.Tecnico;
import br.com.ufla.sgsr.model.Usuario;
import br.com.ufla.sgsr.persistence.ReservaDAO;
import br.com.ufla.sgsr.persistence.SalaDAO;
import br.com.ufla.sgsr.persistence.UsuarioDAO;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;

/**
 *
 * @author CRAUDINENE
 */
public class TelaCadastroSala extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroSala.class.getName());

    /**
     * Creates new form TelaCadastroSala
     */
    public TelaCadastroSala() {
        initComponents();
        Cadastrarusuario.add(radioAluno);
        Cadastrarusuario.add(radioProfessor);
        Cadastrarusuario.add(radioTecnico);
        
        cadastrarsala.add(radioAtivo);
        cadastrarsala.add(radioInativo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cadastrarusuario = new javax.swing.ButtonGroup();
        cadastrarsala = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        radioTecnico = new javax.swing.JRadioButton();
        btnSalvarUsuario = new javax.swing.JButton();
        btnLimparUsuario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        radioAluno = new javax.swing.JRadioButton();
        radioProfessor = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        Identificacaodasala = new javax.swing.JLabel();
        Nomedasala = new javax.swing.JLabel();
        Capacidade = new javax.swing.JLabel();
        Equipamentos = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        txtCapacidade = new javax.swing.JTextField();
        txtEquipamentos = new javax.swing.JTextField();
        radioAtivo = new javax.swing.JRadioButton();
        radioInativo = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        txtNomeSala = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMatriculaUsuario = new javax.swing.JTextField();
        txtSala = new javax.swing.JTextField();
        txtDataReserva = new javax.swing.JFormattedTextField();
        txtHoraInicio = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtHoraFim = new javax.swing.JFormattedTextField();
        btnConfirmarReserva = new javax.swing.JButton();
        btnCancelarReserva = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Dados do Usuário");

        radioTecnico.setText("Técnico");

        btnSalvarUsuario.setText("Cadastrar Usuário");
        btnSalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarUsuarioActionPerformed(evt);
            }
        });

        btnLimparUsuario.setText("Limpar Campos");
        btnLimparUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome Completo:");

        jLabel4.setText("Matrícula:");

        jLabel5.setText("Tipo de Usuário:");

        radioAluno.setText("Aluno");

        radioProfessor.setText("Professor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(radioAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioProfessor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioTecnico))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNomeCompleto)
                                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnSalvarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparUsuario))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel2)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(radioAluno)
                    .addComponent(radioProfessor)
                    .addComponent(radioTecnico))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarUsuario)
                    .addComponent(btnLimparUsuario))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar Usuário", jPanel2);

        Identificacaodasala.setText("Identificação da Sala ");

        Nomedasala.setText("Nome da Sala:");

        Capacidade.setText("Capacidade:");

        Equipamentos.setText("Equipamentos:");

        Status.setText("Status:");

        radioAtivo.setText("Ativo");
        radioAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAtivoActionPerformed(evt);
            }
        });

        radioInativo.setText("Inativa");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar Campos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        txtNomeSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnSalvar)
                        .addGap(295, 295, 295))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nomedasala)
                            .addComponent(Capacidade)
                            .addComponent(Equipamentos)
                            .addComponent(Status))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Identificacaodasala)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCapacidade)
                                .addComponent(txtEquipamentos)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLimpar)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(radioAtivo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radioInativo)))
                                .addComponent(txtNomeSala, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(82, 82, 82))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(Identificacaodasala)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nomedasala)
                            .addComponent(txtNomeSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Capacidade)
                            .addComponent(txtCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Equipamentos))
                    .addComponent(txtEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Status)
                    .addComponent(radioAtivo)
                    .addComponent(radioInativo))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar Sala", jPanel3);

        jLabel1.setText("Dados Reserva");

        jLabel6.setText("Matrícula do Usuário:");

        jLabel7.setText("Sala:");

        jLabel8.setText("Data da Reserva:");

        jLabel9.setText("Horário de Início:");

        txtMatriculaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaUsuarioActionPerformed(evt);
            }
        });

        txtSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaActionPerformed(evt);
            }
        });

        txtDataReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataReservaActionPerformed(evt);
            }
        });

        jLabel10.setText("Horário de Término:");

        txtHoraFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraFimActionPerformed(evt);
            }
        });

        btnConfirmarReserva.setText("Confirmar Reserva");
        btnConfirmarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarReservaActionPerformed(evt);
            }
        });

        btnCancelarReserva.setText("Cancelar");
        btnCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarReservaActionPerformed(evt);
            }
        });

        jLabel11.setText("(yyyy-mm-dd)");

        jLabel12.setText("(HH:mm:ss)");

        jLabel13.setText("(HH:mm:ss)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnConfirmarReserva)
                        .addGap(43, 43, 43)
                        .addComponent(btnCancelarReserva))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtHoraInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMatriculaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                    .addComponent(txtSala)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtDataReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(17, 17, 17)))))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMatriculaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDataReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarReserva)
                    .addComponent(btnCancelarReserva))
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Reserva de Sala", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarUsuarioActionPerformed
        try {
            String nome = txtNomeCompleto.getText();
            String matricula = txtMatricula.getText();

            if (nome.trim().isEmpty() || matricula.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nome e Matrícula são obrigatórios.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Usuario novoUsuario = null;
            if (radioAluno.isSelected()) {
                novoUsuario = new Aluno(nome, matricula);
            } else if (radioProfessor.isSelected()) {
                novoUsuario = new Professor(nome, matricula);
            } else if (radioTecnico.isSelected()) {
                novoUsuario = new Tecnico(nome, matricula);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um Tipo de Usuário.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }

            UsuarioDAO usuarioDAO = new UsuarioDAO();
            usuarioDAO.salvar(novoUsuario);

            JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limparCamposUsuario();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao cadastrar o usuário:\n" + e.getMessage(), "Erro Inesperado", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSalvarUsuarioActionPerformed

    private void radioAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAtivoActionPerformed

    }//GEN-LAST:event_radioAtivoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            // 1. Coletar os dados da tela
            String nome = txtNomeSala.getText(); // Usando os nomes sugeridos
            int capacidade = Integer.parseInt(txtCapacidade.getText());
            String equipamentosInput = txtEquipamentos.getText();
            boolean ativa = radioAtivo.isSelected();

            // 2. Validar se os campos importantes não estão vazios
            if (nome.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "O campo 'Nome da Sala' é obrigatório.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return; // Para a execução do método aqui
            }

            // 3. Preparar os dados para o objeto
            List<String> equipamentos = Arrays.asList(equipamentosInput.split("\\s*,\\s*"));

            // 4. Criar um objeto do tipo Sala com os dados da tela
            Sala novaSala = new Sala(nome, capacidade, equipamentos, ativa);

            // 5. Criar um objeto DAO para fazer a persistência
            SalaDAO salaDAO = new SalaDAO();
            salaDAO.salvar(novaSala);

            // 6. Informar o usuário que deu tudo certo
            JOptionPane.showMessageDialog(this, "Sala cadastrada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            // 7. Limpar os campos para um novo cadastro
            limparCamposSala();

        } catch (NumberFormatException e) {
            // Erro se o usuário digitar texto no campo de capacidade
            JOptionPane.showMessageDialog(this, "O campo 'Capacidade' deve conter apenas números.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Captura outros possíveis erros, como falha no banco de dados
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao salvar a sala:\n" + e.getMessage(), "Erro Inesperado", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Isso ajuda a ver o erro detalhado no console do NetBeans
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCamposSala();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtNomeSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeSalaActionPerformed

    private void btnLimparUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparUsuarioActionPerformed
        limparCamposUsuario();
    }//GEN-LAST:event_btnLimparUsuarioActionPerformed

    private void txtSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaActionPerformed

    private void txtDataReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataReservaActionPerformed

    private void txtHoraFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraFimActionPerformed

    private void btnConfirmarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarReservaActionPerformed
try {
        String matricula = txtMatriculaUsuario.getText().trim();
        String nomeSala = txtSala.getText().trim();
        String data = txtDataReserva.getText().trim(); // formato: 2025-07-14
        String horaInicio = txtHoraInicio.getText().trim(); // formato: 14:00
        String horaFim = txtHoraFim.getText().trim(); // formato: 15:00

        if (matricula.isEmpty() || nomeSala.isEmpty() || data.isEmpty() || horaInicio.isEmpty() || horaFim.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios.");
            return;
        }

        UsuarioDAO usuarioDAO = new UsuarioDAO();
        SalaDAO salaDAO = new SalaDAO();
        ReservaDAO reservaDAO = new ReservaDAO();

        Optional<Usuario> usuarioOpt = usuarioDAO.buscarPorMatricula(matricula);
        if (usuarioOpt.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Usuário não encontrado.");
            return;
        }
        Usuario usuario = usuarioOpt.get();

        Sala sala = salaDAO.buscarPorNome(nomeSala);
        if (sala == null || !sala.isAtiva()) {
            JOptionPane.showMessageDialog(null, "Sala não encontrada ou inativa.");
            return;
        }

        boolean conflito = reservaDAO.verificarConflito(sala.getId(), data, horaInicio, horaFim);
        if (conflito) {
            JOptionPane.showMessageDialog(null, "Já existe uma reserva para essa sala nesse horário.");
            return;
        }

        Reserva reserva = new Reserva();
        reserva.setIdUsuario(usuario.getId());
        reserva.setIdSala(sala.getId());
        reserva.setDataReserva(data);
        reserva.setHoraInicio(horaInicio);
        reserva.setHoraFim(horaFim);
        reserva.setStatus("Confirmada");

        reservaDAO.salvar(reserva);

        JOptionPane.showMessageDialog(null, "Reserva realizada com sucesso!");
        limparCamposReserva();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao realizar reserva: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnConfirmarReservaActionPerformed

    private void btnCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarReservaActionPerformed
        limparCamposReserva();
    }//GEN-LAST:event_btnCancelarReservaActionPerformed

    private void txtMatriculaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaUsuarioActionPerformed


private void limparCamposSala() {
        txtNomeSala.setText("");
        txtCapacidade.setText("");
        txtEquipamentos.setText("");
        cadastrarsala.clearSelection();
    }
  private void limparCamposUsuario() {
    txtNomeCompleto.setText("");
    txtMatricula.setText("");
    Cadastrarusuario.clearSelection();
}

private void limparCamposReserva() {
    txtMatriculaUsuario.setText("");
    txtDataReserva.setText("");
    txtHoraInicio.setText("");
    txtHoraFim.setText("");
    txtSala.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroSala().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Cadastrarusuario;
    private javax.swing.JLabel Capacidade;
    private javax.swing.JLabel Equipamentos;
    private javax.swing.JLabel Identificacaodasala;
    private javax.swing.JLabel Nomedasala;
    private javax.swing.JLabel Status;
    private javax.swing.JButton btnCancelarReserva;
    private javax.swing.JButton btnConfirmarReserva;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimparUsuario;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvarUsuario;
    private javax.swing.ButtonGroup cadastrarsala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton radioAluno;
    private javax.swing.JRadioButton radioAtivo;
    private javax.swing.JRadioButton radioInativo;
    private javax.swing.JRadioButton radioProfessor;
    private javax.swing.JRadioButton radioTecnico;
    private javax.swing.JTextField txtCapacidade;
    private javax.swing.JFormattedTextField txtDataReserva;
    private javax.swing.JTextField txtEquipamentos;
    private javax.swing.JFormattedTextField txtHoraFim;
    private javax.swing.JFormattedTextField txtHoraInicio;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMatriculaUsuario;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JTextField txtNomeSala;
    private javax.swing.JTextField txtSala;
    // End of variables declaration//GEN-END:variables
}